[workspace]
members = [
    "aead",
    "cipher",
    "crypto-common",
    "digest",
    "password-hash",
    "signature",
    "signature/async",
]

[patch.crates-io]
block-buffer = { git = "https://github.com/RustCrypto/utils", branch = "pad_error" }
inout = { git = "https://github.com/RustCrypto/utils", branch = "pad_error" }
